trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  displayName: Install Node.js
  inputs:
    versionSpec: 16.x

- task: PowerShell@2
  displayName: Install CopyFiles & JsonMerge
  inputs:
    targetType: 'inline'
    script: |
      npm install -g copyfiles
      npm install -g jsonmerge

- task: Npm@1
  displayName: Build
  inputs:
    command: custom
    workingDir: $(Build.SourcesDirectory)
    customCommand: run vsix:build

- task: Npm@1
  displayName: Copy
  inputs:
    command: custom
    workingDir: $(Build.SourcesDirectory)
    customCommand: run vsix:copy

- task: ArchiveFiles@2
  displayName: Archive Files
  inputs:
    rootFolderOrFile: $(Build.SourcesDirectory)/out
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/package.zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    publishLocation: Container