trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  displayName: Install Node.js
  inputs:
    versionSpec: 16.x

- script: |
    npm run vsix:build
    npm install -g copyfiles
    npm run vsix:copy
  displayName: Build
  workingDirectory: $(Build.SourcesDirectory)

- task: ArchiveFiles@2
  displayName: Archive Files
  inputs:
    rootFolderOrFile: $(Build.SourcesDirectory)/out
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/package.zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    publishLocation: Container