trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 16.x
  displayName: Install Node.js

- script: npm run vsix:build
  displayName: Build

- script: |
    npm install -g copyfiles
    npm run vsix:copy D:/a/1/s/out
  displayName: Copy

- script: | 
    cd D:/a/1/s/out
    tree /F

- task: ArchiveFiles@2
  displayName: Archive Files
  inputs:
    rootFolderOrFile: out
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/package.zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/package.zip
    ArtifactName: drop
    publishLocation: Container