trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 16.x
  displayName: Install Node.js

- script: |
    npm install
    npm install -g copyfiles
    npm install -g tfx-cli
  displayName: NPM Install

- script: npm run vsix:build
  displayName: Build

- script: npm run vsix:copy
  displayName: Copy

- task: ArchiveFiles@2
  displayName: Archive Files
  inputs:
    rootFolderOrFile: $(Build.BinariesDirectory)/out
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/package.zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/package.zip
    ArtifactName: drop
    publishLocation: Container