trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 16.x
  displayName: Install Node.js

- task: Npm@1
  displayName: Build
  inputs:
    command: 'custom'
    customCommand: npm run vsix:build & npm install -g copyfiles & npm run vsix:copy
    
- script: tree /F

- task: ArchiveFiles@2
  displayName: Archive Files
  inputs:
    rootFolderOrFile: out
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/package.zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/package.zip
    ArtifactName: drop
    publishLocation: Container